### ISSUE TITLE
support for computers using other languages

### ISSUE THREAD

**Issue by Xsmael** [ben-bradley/ping-lite#8]
When I first tried this module it wasnt workin and I wasted quite some to figure out why.
then I found that it was because  my computer(windows) is in french and the regular expression  which you are using to grap the response time ( `/time[><=](.+?)ms/` ) wont work coz this is my ping output:

> Réponse de 8.8.8.8 : octets=32 temps=484 ms TTL=123
> Réponse de 8.8.8.8 : octets=32 temps=653 ms TTL=123
> Réponse de 8.8.8.8 : octets=32 temps=625 ms TTL=123

the quick fix obviously for me was to change **time** to **temps** but it would be awesome if we can have a regex that doesn't rely on the string "time".

Thanks!

**Comment by ben-bradley** [comment]
Hey, thanks for pointing this out. I've updated the regex to look for 
- WIN - `/[><=]([0-9.]+?)ms/`
- LIN - `/=([0-9.]+?) ms/`
- MAC  - `/=([0-9.]+?) ms/`

If you upgrade to `2.0.0` you should get this fix.

**Comment by Xsmael** [comment]
Thanks for the prompt fix, but I think there is a small typo for windows a space is missing right before **ms** 

- WIN - `/[><=]([0-9.]+?)ms/`
- WIN - `/[><=]([0-9.]+?) ms/`

**Comment by ben-bradley** [comment]
Ah, I see. The wildcard `.` match caught that space in the previous version. I'll get `2.0.1` out in a couple minutes.

**Comment by Xsmael** [comment]
Great ! :) now its perfect. 
Just one last thins, this is unrelated but I'm getting this output when I try the examples:

`undefined responded in 160 ms.`
I don't know why host is undefined, its not very important for my use case though.

**Comment by ben-bradley** [comment]
I forget which version of Node was current when I wrote this originally, but it looks like the use of the `this` keyword in the `readme.md` example is no longer valid. I've updated `readme.md` to refer to `ping` instead of `this` and it should work now.

Thanks again for the feedback!

**Comment by Xsmael** [comment]
my pleasure :)

**Comment by ic23** [comment]
@ben-bradley What about the Russian language? It uses "мс" instead of "ms".
![image](https://user-images.githubusercontent.com/21969222/147893648-88ceb885-3d0d-4351-86a1-897f09694d5f.png)

**Comment by ic23** [comment]
Hm...
https://github.com/Jyben/csgo-mm-server-picker/pull/77/commits/c88136c564a22abcfe5d2fc7f1513b429213c3df
